= Handlebars templating
:toc:
:toclevels: 3

[abstract]
This page details Handlebars templating.


== Dependency

[source,xml]
----
<dependency>
  <groupId>io.yupiik.fusion</groupId>
  <artifactId>fusion-handlebars</artifactId>
  <version>${fusion.version}</version>
</dependency>
----

== Usage

It starts from `HandlebarsCompiler` (available as a fusion bean) which compiles a template + its helpers and partials as a `Template` which supports to render the template.

Data can be map of primitives (or data which have a `toString()`) or lists for now.
It tolerates that you pass a `Supplier` too as map value for a lazy evaluation.

[source,java]
----
// once per app
final var compiler = new HandlebarsCompiler();
final var tpl = compiler.compile(new HandlebarsCompiler.CompilationContext(
        new HandlebarsCompiler.Settings()
                .helpers(Map.of( // some helpers - can be Map.of() if you don't use them
                        "uppercase", o -> o.toString().toUpperCase(ROOT)))
                .partials(Map.of(
                        "person", "{{person.name}} is {{person.age}} years old.")),
        "{{firstname}} {{uppercase lastname}}"));

// at runtime
final var rendering = tpl.render(Map.of(...));
----

== Each built-in helper data-variables

`{{#each xxx}}` supports the following data-variables:

* `@first` (boolean): is the current element the first one,
* `@last` (boolean): is the current element the last one,
* `@index` (integer): 0-based index of current element.

If the `xxx` variable is not a `Collection` but a `Map`, the additional `@key` and `@value` data-variables are available.

