= Fusion Testing

[abstract]
Fusion Testing provides a way to start/stop a container for your tests and get injections in your test classes through method parameters or fields (still marked with `@Fusion`).

== Example

[source,java]
----
@FusionSupport
class Mytest {
    @Test
    void run(@Fusion final MyService service) {
        // ...
    }
}
----

== Runner flavors

There are two runner flavors:

* `FusionSupport` which starts and stops the container per test class,
* `MonoFusionSupport` which starts and stops the container per JVM - faster but does not isolate all classes.

[TIP]
--
using a custom JUnit 5 `Extension` where you set system properties in a static block, you can configure the container before it starts.
It is recommended to combine it in a custom annotation to control the ordering and ease the usage:

[source,java]
----
@Target(TYPE)
@Retention(RUNTIME)
@MonoFusionSupport
@ExtendsWith(MyAppSupport.MyConf.class)
public @interface MyAppSupport {
    class MyConf implements Extension {
        static {
            // do the configuration
            System.setProperty("....", "....");
        }
    }
}
----

Then simply replace fusion annotation by `MyAppSupport`.

Alternatively you can register a test `ConfigurationSource` bean if you prefer but this extension option enables to also start global services like dependencies mock or a database.
--

Note that if you need to exclude some module from the discovery (which uses `ServiceLoader`), mono extension reads`yupiik.fusion.mono.modules.discovery.excluded` system property which takes a comma separated list of fully qualified names.

== Testing a Launcher application

Particularly for CLI applications (using an `Launcher` and an `Awaiter` getting `Args` injected for example), you can use `@FusionCLITest` as a replacement of `@Test`.
It will enable you to get an automatic execution of `Launcher` based on the annotation `args` value and to get injected `Stdout` and `Stderr` to validate the outputs.

[source,java]
----
@FusionCLITest(args = {"test", "run"})
void run(final Stdout stdout) {
    assertEquals("...", stdout.content().strip());
}
----


TIP: `args` are made available to `Configuration` thanks a dedicated `ConfigurationSource` which supports these style of arguments (all leading to `foo=bar` mapping):  `--foo bar`,  `-foo bar`, `foo bar`, `--foo=bar`,  `-foo=bar`,  `foo=bar`.
A particular arg starting by `fusion-properties` will be replaced by loading its value (as `Properties`, it can be inline or a file path - preferred).
