/*
 * Copyright (c) 2022 - present - Yupiik SAS - https://www.yupiik.com
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package io.yupiik.fusion.json.schema;

import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Converts a "legacy" JSON schema (the flavor generated by the Fusion annotation processor, i.e. a
 * Draft-07/OpenAPI hybrid using the {@code nullable} keyword and {@code #/schemas/...} or
 * {@code #/definitions/...} references) into a
 * <a href="https://json-schema.org/draft/2020-12/schema">JSON Schema Draft 2020-12</a> document.
 * <p>
 * The conversion is purely structural and reflectionless: it walks a generic JSON tree (i.e. the
 * {@code Map}/{@code List}/scalar values produced by the Fusion JSON codecs) and builds a new tree. The JSON values
 * (enum members, {@code const}, {@code default}, examples...) are never altered, only the schema keywords are
 * rewritten.
 * <p>
 * The targeted changes are:
 * <ul>
 *     <li>{@code "nullable": true} becomes {@code "type": ["<base>", "null"]} (2020-12 removed {@code nullable} in
 *     favor of {@code type} unions). A node with only {@code nullable} (no {@code type}) collapses to
 *     {@code "type": "null"}.</li>
 *     <li>{@code "definitions"} is renamed {@code "$defs"} and a {@code "schemas"} container (used by the generated
 *     OpenRPC/CRD outputs) is likewise emitted as {@code "$defs"}.</li>
 *     <li>{@code "$ref": "#/definitions/..."} and {@code "$ref": "#/schemas/..."} references are relocated to
 *     {@code "$ref": "#/$defs/..."}.</li>
 *     <li>a {@code "$schema": {@link #SCHEMA_2020_12}} header is added at the root when not already present.</li>
 * </ul>
 * <p>
 * For the typed flavor, {@link RawBuildJsonSchema} (and its hand-written {@link RawBuildJsonSchemaJsonCodec}) is the
 * compile-free mirror of the processor-generated schema. Pass a {@code META-INF/fusion/json/schemas.json} bundle (a
 * {@code {"schemas": {<fqn>: <schema>, ...}}} object, deserialized by a {@link io.yupiik.fusion.json.JsonMapper}) to
 * {@link #to2020Bundle(Map)} to obtain a self-contained 2020-12 document whose shared definitions live under a root
 * {@code $defs}.
 * <p>
 * This class is registered as an application-scoped bean once {@code fusion-json} is on the classpath and can also
 * be instantiated directly.
 *
 * @see io.yupiik.fusion.json.schema.validation.JsonSchemaValidatorFactory
 */
public class JsonSchemaService {
    /**
     * The {@code $schema} URI emitted on converted root documents.
     */
    public static final String SCHEMA_2020_12 = "https://json-schema.org/draft/2020-12/schema";

    /**
     * Converts the given schema (a generic JSON tree, usually a {@code Map<String, Object>}) into a Draft 2020-12
     * schema.
     *
     * @param raw the schema to convert, as a generic JSON tree.
     * @return the converted value (typically a {@code Map<String, Object>}).
     */
    public Object toJsonSchema202012(final Object raw) {
        return raw == null ? null : nodeTo2020(raw, true);
    }

    /**
     * Converts the given schema (a generic JSON object, e.g. the output of a {@code JsonMapper}) into a Draft 2020-12
     * schema.
     *
     * @param raw the schema to convert.
     * @return the converted schema root.
     */
    public Map<String, Object> toJsonSchema202012(final Map<String, Object> raw) {
        return (Map<String, Object>) toJsonSchema202012((Object) raw);
    }

    /**
     * Converts a single typed, processor-emitted schema into a Draft 2020-12 schema.
     *
     * @param schema the typed schema to convert.
     * @return the converted schema root.
     */
    public Map<String, Object> toJsonSchema202012(final RawBuildJsonSchema schema) {
        return toJsonSchema202012(rawToMap(schema));
    }

    /**
     * Converts a collection of typed, processor-emitted schemas into a self-contained Draft 2020-12 document whose
     * definitions are shared under a root {@code $defs}; each schema is keyed by its {@code $id} and every
     * {@code #/schemas/<fqn>} reference now points into that {@code $defs} map.
     *
     * @param schemas the schemas to convert.
     * @return a document with a {@code $schema} header and a root {@code $defs} map.
     */
    public Map<String, Object> toJsonSchema202012(final Collection<RawBuildJsonSchema> schemas) {
        final var defs = new LinkedHashMap<String, Object>();
        for (final var schema : schemas) {
            if (schema != null && schema.id() != null) {
                // each member is a plain (non-root) schema: no $schema header within $defs,
                // and no embedded $id since the $defs key already identifies it (avoids an accidental nested scope)
                final var converted = (Map<String, Object>) nodeTo2020(rawToMap(schema), false);
                converted.remove("$id");
                defs.put(schema.id(), converted);
            }
        }
        final var out = new LinkedHashMap<String, Object>();
        out.put("$schema", SCHEMA_2020_12);
        out.put("$defs", defs);
        return out;
    }

    /**
     * Converts a whole {@code META-INF/fusion/json/schemas.json} bundle tree ({@code {"schemas": {<fqn>: <schema>,
     * ...}}}) into a self-contained Draft 2020-12 document. Deserialize the file with a
     * {@link io.yupiik.fusion.json.JsonMapper} first and pass the resulting {@code Map} here.
     *
     * @param bundle the parsed bundle tree.
     * @return the converted document with a root {@code $defs} map.
     */
    public Map<String, Object> to2020Bundle(final Map<String, Object> bundle) {
        final var schemas = toTypedSchemas(bundle);
        return toJsonSchema202012(schemas);
    }

    /**
     * Converts a bundle tree ({@code {"schemas": {...}}}) into the list of its typed schemas.
     *
     * @param bundle the parsed bundle tree.
     * @return the typed schemas contained in the bundle (empty when the {@code schemas} member is absent).
     */
    @SuppressWarnings("unchecked")
    public List<RawBuildJsonSchema> toTypedSchemas(final Map<String, Object> bundle) {
        final var schemas = (Map<String, Object>) bundle.get("schemas");
        final var out = new ArrayList<RawBuildJsonSchema>();
        if (schemas != null) {
            for (final var entry : schemas.entrySet()) {
                final var typed = RawBuildJsonSchema.fromJsonTree(entry.getValue());
                out.add(typed.id() == null ? new RawBuildJsonSchema(
                        entry.getKey(), typed.ref(), typed.type(), typed.nullable(), typed.format(), typed.pattern(),
                        typed.additionalProperties(), typed.properties(), typed.items(), typed.title(),
                        typed.description(), typed.enumeration(), typed.required()) : typed);
            }
        }
        return out;
    }

    private Object nodeTo2020(final Object value, final boolean isRoot) {
        if (value instanceof Map<?, ?> map) {
            return mapTo2020((Map<String, Object>) map, isRoot);
        }
        if (value instanceof List<?> list) {
            final var out = new ArrayList<Object>(list.size());
            for (final var item : list) {
                out.add(nodeTo2020(item, false));
            }
            return out;
        }
        return value;
    }

    private Map<String, Object> mapTo2020(final Map<String, Object> schema, final boolean isRoot) {
        final var out = new LinkedHashMap<String, Object>();
        for (final Map.Entry<String, Object> entry : schema.entrySet()) {
            final var key = entry.getKey();
            final var value = entry.getValue();
            switch (key) {
                case "nullable" -> {
                    // applied after reading the whole node since it depends on "type"
                }
                case "definitions", "schemas" -> out.put("$defs", nodeTo2020(value, false));
                case "$ref" -> out.put("$ref", relocateRef(String.valueOf(value)));
                default -> out.put(key, nodeTo2020(value, false));
            }
        }

        if (schema.get("nullable") instanceof Boolean b && b) {
            final var currentType = out.get("type");
            if (currentType instanceof String s) {
                out.put("type", List.of(s, "null"));
            } else if (currentType instanceof List<?> list && !containsString(list, "null")) {
                final var newType = new ArrayList<Object>(list);
                newType.add("null");
                out.put("type", newType);
            } else if (!out.containsKey("type") && !out.containsKey("$ref")) {
                // a nullable node without any other type - only the "null" alternative is expressible
                out.put("type", "null");
            }
        }
        out.remove("nullable");

        if (isRoot && !out.containsKey("$schema")) {
            out.put("$schema", SCHEMA_2020_12);
        }
        return out;
    }

    private Map<String, Object> rawToMap(final RawBuildJsonSchema schema) {
        final var out = new LinkedHashMap<String, Object>();
        if (schema.id() != null) {
            out.put("$id", schema.id());
        }
        if (schema.ref() != null) {
            out.put("$ref", schema.ref());
        }
        if (schema.type() != null) {
            out.put("type", schema.type());
        }
        if (schema.nullable() != null) {
            out.put("nullable", schema.nullable());
        }
        if (schema.format() != null) {
            out.put("format", schema.format());
        }
        if (schema.pattern() != null) {
            out.put("pattern", schema.pattern());
        }
        if (schema.additionalProperties() != null) {
            out.put("additionalProperties", toJsonTree(schema.additionalProperties()));
        }
        if (schema.properties() != null) {
            final var props = new LinkedHashMap<String, Object>();
            for (final var entry : schema.properties().entrySet()) {
                props.put(entry.getKey(), rawToMap(entry.getValue()));
            }
            out.put("properties", props);
        }
        if (schema.items() != null) {
            out.put("items", rawToMap(schema.items()));
        }
        if (schema.title() != null) {
            out.put("title", schema.title());
        }
        if (schema.description() != null) {
            out.put("description", schema.description());
        }
        if (schema.enumeration() != null) {
            out.put("enum", List.copyOf(schema.enumeration()));
        }
        if (schema.required() != null) {
            out.put("required", List.copyOf(schema.required()));
        }
        return out;
    }

    private Object toJsonTree(final Object value) {
        if (value instanceof RawBuildJsonSchema s) {
            return rawToMap(s);
        }
        return value;
    }

    private String relocateRef(final String ref) {
        if (ref.startsWith("#/definitions/")) {
            return "#/$defs/" + ref.substring("#/definitions/".length());
        }
        if (ref.startsWith("#/schemas/")) {
            return "#/$defs/" + ref.substring("#/schemas/".length());
        }
        return ref;
    }

    private boolean containsString(final List<?> values, final String expected) {
        return values.stream().anyMatch(expected::equals);
    }
}